//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleverSlothProject) DeepCopyInto(out *CleverSlothProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleverSlothProject.
func (in *CleverSlothProject) DeepCopy() *CleverSlothProject {
	if in == nil {
		return nil
	}
	out := new(CleverSlothProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CleverSlothProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleverSlothProjectList) DeepCopyInto(out *CleverSlothProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CleverSlothProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleverSlothProjectList.
func (in *CleverSlothProjectList) DeepCopy() *CleverSlothProjectList {
	if in == nil {
		return nil
	}
	out := new(CleverSlothProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CleverSlothProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleverSlothProjectSpec) DeepCopyInto(out *CleverSlothProjectSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleverSlothProjectSpec.
func (in *CleverSlothProjectSpec) DeepCopy() *CleverSlothProjectSpec {
	if in == nil {
		return nil
	}
	out := new(CleverSlothProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleverSlothProjectStatus) DeepCopyInto(out *CleverSlothProjectStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleverSlothProjectStatus.
func (in *CleverSlothProjectStatus) DeepCopy() *CleverSlothProjectStatus {
	if in == nil {
		return nil
	}
	out := new(CleverSlothProjectStatus)
	in.DeepCopyInto(out)
	return out
}
